#++
#  DESCRIPTION: Settings for MODBUS TCP-to-RTU gateway
#
#  AUTHOR: Ruslan R.  Laishev
#
#  CREATION DATE: 10-SEP-2025
#
#  MODIFICATION  HISTORY:
#
#--


#
#
#

listeners = (					# A listeners to accept remote request, pass to local device, and return response
	{
	bind = "TCP:0.0.0.0:502";		# Listen on the port TCP #502
	connlm = 8;				# A maximum number of connections from remote clients
	iotmo = 5000;				# A timeout for network I/O operations, milliseconds
	target = "/dev/ttyUSB0";		# Target serial (must be defined in the <serials> section!)
	},

	{bind = "TCP:0.0.0.0:503"; connlm = 8; iotmo = 5000; target = "/dev/ttyS1";},
	{bind = "TCP:0.0.0.0:504"; connlm = 8; iotmo = 5000; target = "/dev/ttyS0";}
);



serials = (
	{	desc = "A control channel to meteostation";
		device = "/dev/ttyUSB0";	# OS device name, eg: COM1, /dev/ttyS0 ...
		chars = "9600, 8, N, 1";	# <Speed, bits in byte, parity checking, stop bits>
		flow = "NONE";			# Flow control: NONE, XON/XOFF, RTS/CTS, DSR/DTR
		iotmo = 5000;			# I/O timeout, milliseconds (msec-s)

		rs485 = 0;			# 1: Enable RS485 specific support


		addts = 1;			# 1: Add timestamp to response PDU
		ts_fncode = 4;			#
		ts_base_reg0 = 135;		# 135: Id of pseudo-register with TS
	}

);
