/*
**++
**  FACILITY: A yet another TCP to RTU gateway for MODBUS
**
**  DESCRIPTION: The message catalogue of the T2R facility (number 138). Every record is
**	FAO-styled and is signalled via $PUTMSG_FAO. New messages are added strictly at the end
**	of the __DEF_MESSAGES__ macro: the message numbers are generated by __COUNTER__ and must
**	stay stable between the deliveries.
**
**  AUTHORS: StarLet Squad and Ruslan R. Laishev (AKA: BadAss sysman)
**
**  MODIFICATION HISTORY:
**
**	25-AUG-2026	RRL	X.00-06 / REV: 00.06.00 - Added the FAO-styled messages block for the
**				operational troubleshooting: REVISNF, DEVOPNERR, DEVREADY, NOANSWER,
**				FRAMETMO, BADFRAME, CRC16ERR, EXCRPT, LSNRRDY, LSNRERR, EXITST.
**
**	25-AUG-2026	RRL	X.00-07 / REV: 00.07.00 - The catalogue is FAO-only now: the never used
**				printf-styled records (NETLSNR, NETERROR, RNF, NOLAN, LINKERR, CRCERR,
**				REVISION, LOGFILE) are removed; FULLMBAP is kept (a status constant),
**				NETCONN/NETDISCN are recreated as the FAO records and are signalled
**				at the accept/disconnect points of T2R-NET.
**
**--
*/

#ifndef	__T2R_MSGS__
#define __T2R_MSGS__	1

#include	"utility_routines.h"		/* STS$K-* constants */
#include	"t2r_defs.h"			/* T2R common definitions */

#ifdef __cplusplus
extern "C" {
#endif

#define	T2R		138			/* Facility number ! This number is should be unique */

/*	Attention !!! Place new messages at end of this macro !!! */
/*	<facility>, <severity>, <abbreviation>, <message text with the FAO directives> */

/*
 * ALL the records are FAO-styled and are signalled via $PUTMSG_FAO ONLY. See the User Guide
 * (docs/) for the per-code description.
 */
#define __DEF_MESSAGES__ \
\
$DEF_MSG(T2R, SUCCESS,	FULLMBAP,		"Whole MBAP packet is in the buffer")\
$DEF_MSG(T2R, SUCCESS,	NETCONN,		"[#!SL] Accept client connection !%I:!UW (listener #!SL)")\
$DEF_MSG(T2R, SUCCESS,	NETDISCN,		"[#!SL] Disconnect client connection !%I:!UW")\
\
$DEF_MSG(T2R, INFO,	REVISNF,		"Rev: !AC (REV: !AC)") \
$DEF_MSG(T2R, ERROR,	DEVOPNERR,		"Cannot open the device <!AZ>, errno: !SL") \
$DEF_MSG(T2R, SUCCESS,	DEVREADY,		"Device <!AZ> [!UL baud, answer tmo: !UL msec, t3.5: !UL usec] --- is ready") \
$DEF_MSG(T2R, ERROR,	NOANSWER,		"[#!SL:<!AZ>] Did not get an answer in !UL msec --- abort I/O operation") \
$DEF_MSG(T2R, WARN,	FRAMETMO,		"[#!SL:<!AZ>] Frame is not completed in !UL msec (!UL octets so far)") \
$DEF_MSG(T2R, ERROR,	BADFRAME,		"[#!SL:<!AZ>] Illformed RTU frame length: !UL octets, allowed [!UL..!UL]") \
$DEF_MSG(T2R, ERROR,	CRC16ERR,		"[#!SL:<!AZ>] RTU CRC16 check error (received: !XW, calculated: !XW)") \
$DEF_MSG(T2R, WARN,	EXCRPT,			"[#!SL:<!AZ>] Report exception !UL (!AZ) to the network requester") \
$DEF_MSG(T2R, SUCCESS,	LSNRRDY,		"[#!SL] Listener !%I:!UW [Target: <!AZ>] --- is ready") \
$DEF_MSG(T2R, ERROR,	LSNRERR,		"Listener !%I:!UW --- !AZ error, errno: !SL") \
$DEF_MSG(T2R, INFO,	EXITST,			"Exit with exit_flag: !SL, rc: !XL") \





enum						/* Generate messages number constants */
{
	#define	$DEF_MSG(f, s, c, t)	f##$__##c = ( (f << 16) | (__COUNTER__<< 3) | STS$K_##s),
	__DEF_MESSAGES__
	#undef	$DEF_MSG

};


#ifdef __cplusplus
}
#endif

#endif	/*	__T2R_MSGS____	*/

